# Generated by Django 5.2.1 on 2025-06-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
