# Generated by Django 6.0.3 on 2026-03-25 04:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0004_video_hls_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="upload_date",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="video",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private"), ("unlisted", "Unlisted")],
                db_index=True,
                default="public",
                max_length=10,
            ),
        ),
    ]
