# Generated by Django 6.0.3 on 2026-06-11 02:43

from django.db import migrations, models
from django.utils.text import slugify


def backfill_empty_category_slugs(apps, schema_editor):
    """修補 allow_unicode 之前建立的中文分類：當時 slugify 會產出空字串 slug。"""
    Category = apps.get_model("videos", "Category")
    for category in Category.objects.filter(slug=""):
        category.slug = slugify(category.name, allow_unicode=True)
        category.save(update_fields=["slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0006_video_hls_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True),
        ),
        migrations.RunPython(backfill_empty_category_slugs, migrations.RunPython.noop),
    ]
