# Generated by Django 6.0.3 on 2026-06-11 04:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        ("videos", "0007_alter_category_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private"), ("unlisted", "Unlisted")],
                default="public",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(fields=["visibility", "-upload_date"], name="video_vis_upload_idx"),
        ),
    ]
