# Generated by Django 6.0.3 on 2026-06-11 05:48

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        ("videos", "0008_alter_video_visibility_video_video_vis_upload_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # gin_trgm_ops 需要 pg_trgm extension，makemigrations 不會自動生成
        TrigramExtension(),
        migrations.AddIndex(
            model_name="video",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("title"), name="gin_trgm_ops"
                ),
                name="video_title_trgm_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("description"), name="gin_trgm_ops"
                ),
                name="video_desc_trgm_idx",
            ),
        ),
    ]
