# Generated by Django 6.0.3 on 2026-03-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userprofile_banner_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="subscriber_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
