# Generated by Django 6.0.3 on 2026-03-24 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0006_notification_sender'),
        ('videos', '0004_video_hls_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likedislike',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='likedislike',
            constraint=models.UniqueConstraint(fields=('video', 'user'), name='unique_likedislike_per_video_user'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('subscriber', 'subscribed_to'), name='unique_subscription_per_user_pair'),
        ),
    ]
