# Generated by Django 6.0.3 on 2026-03-25 04:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interactions", "0007_alter_likedislike_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="timestamp",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
