# Generated by Django 6.0.3 on 2026-06-11 04:12

import json

from django.db import migrations, models


def ensure_message_is_valid_json(apps, schema_editor):
    """早期版本（consumers 同步建立通知的年代）可能存過純文字 message，
    先包成 JSON 字串，否則 AlterField 的 ALTER ... USING message::jsonb 會失敗。"""
    Notification = apps.get_model("interactions", "Notification")
    for notification in Notification.objects.all().iterator():
        try:
            json.loads(notification.message)
        except (TypeError, ValueError):
            notification.message = json.dumps(notification.message)
            notification.save(update_fields=["message"])


class Migration(migrations.Migration):
    dependencies = [
        ("interactions", "0010_flatten_nested_replies"),
    ]

    operations = [
        migrations.RunPython(ensure_message_is_valid_json, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.JSONField(),
        ),
    ]
